//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Practise.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12767453_541301039384137_1293386704_n {
            get {
                object obj = ResourceManager.GetObject("12767453_541301039384137_1293386704_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1441243_1869344913291943_7424727935859789113_n {
            get {
                object obj = ResourceManager.GetObject("1441243_1869344913291943_7424727935859789113_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1897752_503141349866773_2989622709271290271_n {
            get {
                object obj = ResourceManager.GetObject("1897752_503141349866773_2989622709271290271_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1E3HNp0 {
            get {
                object obj = ResourceManager.GetObject("1E3HNp0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__2_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__2_1 {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__3_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__3_1 {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__4_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__5_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__6_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__7_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy__8_ {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy (" +
                        "8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy1 {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set___Copy2 {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set - Copy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8687961_Drum_kit_isolated_on_white_background_Stock_Photo_drum_drums_set1 {
            get {
                object obj = ResourceManager.GetObject("8687961-Drum-kit-isolated-on-white-background-Stock-Photo-drum-drums-set1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0839 {
            get {
                object obj = ResourceManager.GetObject("IMG_0839", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_8158_copy {
            get {
                object obj = ResourceManager.GetObject("IMG_8158 copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_1982045_web {
            get {
                object obj = ResourceManager.GetObject("logo_1982045_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled___Copy {
            get {
                object obj = ResourceManager.GetObject("Untitled - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled1 {
            get {
                object obj = ResourceManager.GetObject("Untitled1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy___Copy {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy___Copy1 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy - Copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy___Copy2 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy - Copy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy___Copy3 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy - Copy3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy___Copy4 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy - Copy4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy1 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy2 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xfgh___Copy3 {
            get {
                object obj = ResourceManager.GetObject("xfgh - Copy3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
